### ISSUE TITLE
Nav bar blocked by something when scroll down

### ISSUE THREAD

**Issue by ziyuan-linn** [ml5js/ml5-website-v02-gatsby#34]
Hi ml5 web team,

When scrolling down on the landing page, I noticed that the nav bar became partially blocked and couldn't be clicked. Please see the video below.

https://github.com/user-attachments/assets/48f78273-3ea8-48a6-b9c6-63c05b4c6ba2

I think the breaking changes notice is what's blocking it.

**Comment by MOQN** [comment]
Thank you for letting us know! It seems like it’s blocked by the banner. I will fix it soon!

**Comment by alanvww** [comment]
Thank you for finding this issue! Yes, it looks like even the banner is translated, but still blocking the area. 

@MOQN It could be a quick fix by adding style `display:none` right after the banner fades out. I do have time to fix it tomorrow after. Let me know if anything I can help!

**Comment by MOQN** [comment]
Thank you @alanvww @ziyuan-linn once again :D
