### ISSUE TITLE
Deployment!

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v02-gatsby#4]
Hi everyone! I've deployed the gatsby site to netlify, take a look!

https://ml5-next-gen.netlify.app/

I will set this up with preview deploy builds and we can move it to ml5js.org when the time comes!

I can invite team members to Netlify too let's discuss!

**Comment by MOQN** [comment]
Amazing! Thank you!

**Comment by shiffman** [comment]
This issue can be closed just wanted to communicate to the team that i had it setup! Looking forward to getting the site live!
