### ISSUE TITLE
Community Project: Patt Vira videos

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v02-gatsby#40]
### Update Type

Content

### Description

I would like to propose @pattvira's videos for the community page!

https://www.youtube.com/playlist?list=PL0beHPVMklwhxJ6G3Hn4uLQTDe4Y562Dr

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MOQN** [comment]
It was included in the [PR #39](https://github.com/ml5js/ml5-website-v02-gatsby/pull/39), and featured on the Home page.

@shiffman is there any way to get the original thumbnail image? I had to screen-capture it. Also could you think of a description for the video tutorials? (This is optional, though!)

**Comment by shiffman** [comment]
Hi @MOQN I can provide the thumbnail, but I might suggest using an image from one of Patt's other videos since I'm already featured in the videos from my channel! @pattvira do you have a preference?

**Comment by pattvira** [comment]
Thanks so much for starting the thread Dan @shiffman! 

Hi @MOQN, here is a thumbnail for one of my videos! Also, is it possible to edit the name and description to this?

Name: Coding Tutorial Playlist with ml5.js 
Description: This playlist demonstrates how to use ml5.js for web-based machine learning as well as showcasing how you can combine it with other libraries like p5.js for creative coding and matter.js for physics simulations. Each tutorial is designed to be very interactive and fun, guiding you through exciting projects that show how these tools can work together seamlessly to bring your creative ideas to life.
![ct115](https://github.com/user-attachments/assets/8db24b74-05b8-417d-8583-55f2f65fc2ea)

**Comment by MOQN** [comment]
@shiffman Thanks for mentioning this! 

@pattvira Thank you for providing the text and image! The website has been updated with them!

**Comment by pattvira** [comment]
Looks great. Thanks so much!
