### ISSUE TITLE
Font Family "Arvo" doesn't work on some browsers

### ISSUE THREAD

**Issue by MOQN** [ml5js/ml5-website-v02-gatsby#46]
The font family "Arvo" doesn't work on Safari and other browsers.

**Comment by alanvww** [comment]
Hi Moon. I just tried to reproduce it on different browsers on both Mac OS and Windows, and it looks like it works on my end. Can you elaborate more on this issue?

**Comment by MOQN** [comment]
@alanvww, thank you for taking a look at this issue. This is what I see on Safari...

![Uploading Screenshot 2024-10-28 at 1.37.46 AM.png…](Screenshot)

**Comment by MOQN** [comment]
@alanvww, Thank you for your DM! You were right. Apparently the font family has been applied correctly. I just realized that the other browsers render the font-weight differently.

Please view the screenshots below. The above is Google Chome and the bottom is Safari.

`font-weight: 700 (or 600, or bold)`
<img width="1278" alt="font-weight-600" src="https://github.com/user-attachments/assets/034e5759-368c-42b1-981d-70cd0a11c807">

`font-weight: 500 (or below)`
<img width="1280" alt="font-weight-500" src="https://github.com/user-attachments/assets/65918471-0db9-4d5f-96e4-0cc7b7f85bc4">

**Comment by MOQN** [comment]
This is resolved. Thank you @alanvww !!

**Comment by MOQN** [comment]
@alanvww I also updated the font styles of the documentation website on Docsify. By mistake, I pushed the updates directly to the main. (Sorry!) You can see the changes [here](https://github.com/ml5js/ml5-website-v02-docsify/commit/28412b909bd3688217fcf42a7ee0435879ff2679).

Please review the pages and check if there are still some issues with font (or other) styles.

@QuinnHe @myrahsa cc'd!

**Comment by alanvww** [comment]
> @alanvww I also updated the font styles of the documentation website on Docsify. By mistake, I pushed the updates directly to the main. (Sorry!) You can see the changes [here](https://github.com/ml5js/ml5-website-v02-docsify/commit/28412b909bd3688217fcf42a7ee0435879ff2679).
> 
> 
> 
> Please review the pages and check if there are still some issues with font (or other) styles.
> 
> 
> 
> @QuinnHe @myrahsa cc'd!

Will do! Thanks Moon😊
