### ISSUE TITLE
iframe p5 sketch loading issue

### ISSUE THREAD

**Issue by MOQN** [ml5js/ml5-website-v02-gatsby#6]
The p5 sketch in the iframe doesn't load when coming back from a Docisy page.

**Comment by alanvww** [comment]
Fixed in #10 
[Preview Deployment](https://deploy-preview-10--ml5-next-gen.netlify.app/)

**Comment by MOQN** [comment]
@alanvww Thank you! This is fantastic. Can you apply `max-width: 800px` for the `iframe` module?

**Comment by alanvww** [comment]
@MOQN I just tried a little more time with my deploy preview and I believe the sketch is loading correctly when the user go back from the docsify page now.(It didn't fail on my device :/) But for the problem in "open in new page", it shows the same error that 

> DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

This is actually quite interesting and I would like to explore it more besides working on the content. In the meantime, maybe we can try to review the p5 sketch code together?

**Comment by MOQN** [comment]
@alanvww Thank you! Absolutely. Please feel free to look at [this code](https://github.com/MOQN/ml5-website-hero/tree/main/sketch). I got an idea for solving it. Let me explore it and share the details soon.

**Comment by MOQN** [comment]
The hero sketch was newly developed with @XiaozaoWang's hand sketches.
