### ISSUE TITLE
DAIL Center credit

### ISSUE THREAD

**Issue by gohai** [ml5js/ml5-website-v02-gatsby#8]
The center asked all recipients of their grants to acknowledge their funding with

> "This work is partially supported by Shanghai Frontiers Science Center of Artificial Intelligence and Deep Learning at NYU Shanghai."

It'd be great if we could include this on the page (as minute as the sum ultimately was).

**Comment by MOQN** [comment]
@gohai Do you think this can just appear on the About page? Should it be included to all of the footers?

**Comment by gohai** [comment]
About seems very sensible. Thank you for thinking of this!

**Comment by MOQN** [comment]
Thank you for your prompt response! I will add it to About.

**Comment by MOQN** [comment]
It was added. Closing this issue.
